#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Op {
    RETURN = 0,
    CONSTANT = 1,
    NEGATE = 2,
    ADD = 3,
    SUBTRACT = 4,
    MULTIPLY = 5,
    DIVIDE = 6,
    NIL = 7,
    TRUE = 8,
    FALSE = 9,
    NOT = 10,
    EQUAL = 11,
    GREATER = 12,
    LESS = 13,
    PRINT = 14,
    POP = 15,
    DEFINE_GLOBAL = 16,
    GET_GLOBAL = 17,
    SET_GLOBAL = 18,
    GET_LOCAL = 19,
    SET_LOCAL = 20,
    JUMP_IF_FALSE = 21,
    JUMP = 22,
    LOOP = 23,
    CALL = 24,
    CLOSURE = 25,
    GET_UPVALUE = 26,
    SET_UPVALUE = 27,
    CLOSE_UPVALUE = 28,
}
